### ISSUE TITLE
Application validation did not succeed

### ISSUE THREAD

**Issue by Qwerty-Space** [RoxasShadow/SauceNao-Windows#6]
Hi, I contacted you on Twitter.

```
PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///D:/Downloads/SauceNao-Windows-0.1.5.0/SauceNao-Windows/bin/Debug/app.publish/SauceNao-Windows.application
	Application url			: file:///D:/Downloads/SauceNao-Windows-0.1.5.0/SauceNao-Windows/bin/Debug/app.publish/Application%20Files/SauceNao-Windows_0_1_5_0/SauceNao-Windows.exe.manifest

IDENTITIES
	Deployment Identity		: SauceNao-Windows.application, Version=0.1.5.0, Culture=neutral, PublicKeyToken=149cffc35d72334c, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\Downloads\SauceNao-Windows-0.1.5.0\SauceNao-Windows\bin\Debug\app.publish\SauceNao-Windows.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [12/01/2017 00:06:17] : Activation of D:\Downloads\SauceNao-Windows-0.1.5.0\SauceNao-Windows\bin\Debug\app.publish\SauceNao-Windows.application has started.
	* [12/01/2017 00:06:17] : Processing of deployment manifest has successfully completed.
	* [12/01/2017 00:06:17] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/01/2017 00:06:17] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

```

**Comment by RoxasShadow** [comment]
Thanks for the log – we need to regenerate the setup with an updated manifest. Right now I don't have a Windows machine with me so I can't promise you that this issue will be solved very soon, but I'll try to think something for it.

**Comment by Qwerty-Space** [comment]
I might be able to help

**Comment by RoxasShadow** [comment]
Thanks, fortunately I managed to setup a VM with Windows 10.
 
The debug program worked to me, while the setup.exe didn't. To solve the problem, I published it again with a new manifest and some new metadata: please tell me if [this setup.exe](https://github.com/RoxasShadow/SauceNao-Windows/blob/1.6.0/SauceNao-Windows/publish/setup.exe?raw=true) works for you and if its text is in English.

**Comment by Qwerty-Space** [comment]
That setup.exe doesn't have the initial installer part that the other one did, so I couldn't tell.  And it still doesn't work.
```

PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///D:/Downloads/SauceNao-Windows-0.1.5.0/SauceNao-Windows/publish/SauceNao-Windows.application
	Application url			: file:///D:/Downloads/SauceNao-Windows-0.1.5.0/SauceNao-Windows/publish/Application%20Files/SauceNao-Windows_0_1_5_0/SauceNao-Windows.exe.manifest

IDENTITIES
	Deployment Identity		: SauceNao-Windows.application, Version=0.1.5.0, Culture=neutral, PublicKeyToken=149cffc35d72334c, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\Downloads\SauceNao-Windows-0.1.5.0\SauceNao-Windows\publish\SauceNao-Windows.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [14/01/2017 17:29:06] : Activation of D:\Downloads\SauceNao-Windows-0.1.5.0\SauceNao-Windows\publish\SauceNao-Windows.application has started.
	* [14/01/2017 17:29:06] : Processing of deployment manifest has successfully completed.
	* [14/01/2017 17:29:06] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [14/01/2017 17:29:06] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, SauceNao-Windows.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.



```

**Comment by RoxasShadow** [comment]
Please get `SauceNao-Windows.zip` from https://github.com/RoxasShadow/SauceNao-Windows/releases/tag/0.6.1.2, should finally work. Sorry again.

**Comment by RoxasShadow** [comment]
I just built a proper installer for this. I wrote about it in the README file.

**Comment by Qwerty-Space** [comment]
Thank you!
